# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5843cc82eb0c0b462e4801a990f47034ab567da7e62a1bcc9df0c90a612a3015d94c4ff81ff56d1f9c7e098fad340a0a97eed62efbc6882b43d16de8048b50f5

test:
  secret_key_base: 9be5629201d168fbc039d3d5f17891352fc435d7c662c549fd45b6cb75a40e7011e44152c849e28aa580d18dec783269f08b58fba42032efa1a0813137a7b75b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
